### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai-191-korolov#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
5) Відомо, що з серпня 2021 року GitHub-сервер пропонує PAT 
для процесу аутентифікації під час безпечного оновлення GitHub-репозиторію. 
Поясніть, будь ласка, чому так було зроблено?

**Comment by Olexsays** [comment]
Якщо проводити аутентифікацію через PAT замість пароля або SSH-ключа, це дозволить зменшити ризик викрадення облікових даних та підвищити безпеку через декілька причин: 1. Самі по собі паролі можуть бути слабкими, та легко піддаються атакам перебору й можуть бути скомпрометовані. Використання персонального токену зменщує кількість використання слабких паролів і є більш надійними, бо й доступ до них надається один раз при створенні. 2. Також PAT надає гнучний контроль над рівнем доступу до репозиторію. При створенні токена можна обмежити права доступу, які відповідають конкретним діям яких ми очікуємо від роботи з репозиторієм на даному етапі. Тобто, використання PAT надає одночасно більше гнучкості ло роботи із репозиторієм, та безпеки.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
