### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by Olexsays** [oleksandrblazhko/ai-191-korolov#5]
1. Використання криптографічних методів: вимога забезпечена завдяки протоколу HTTPS, який використовує шифрування TLS/SSL, та використанню криптографічноїї бібліотеки для шифрування інформаціних даних засобами Google API
2. Збереження журналів або історичних наборів даних: вимога не виконана, бо не всі дії користувачів заносяться у журнал подій
3. Призначення певних функцій для різних модулів: вимога виконана, бо було проведено розділення функціональності на модулі та обмеження доступу до цих модулів за допомогою різних рівнів авторизації та ролей користувачів: студент / адміністратор тощо.
4. Обмеження зв'язку між деякими областями програми: вимога виконана на рівні надання доступу до бази даних згідно з потребою звертання до неї.
5. Перевірка цілісності даних для критичних змінних: вимога виконана через валідацію вхідних даних і перевірку на наявність потенційно шкідливого коду або SQL-ін'єкцій.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
